# -*- coding: utf-8 -*-
"""notebook1_pytorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hxO7oLBC5WUhl7i9t9x0U_tIgpzmffg6
"""

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""###different types of Tensors

"""

#scalar Tensor
scalar=torch.tensor(7)
#Tensors in pytorch are created using torch.tensor()
scalar

print(f"scalar.item() converts tensors to python integers -> {scalar.item()}")
print(f"scalar.ndim gives dimension of the tensor named scalar -> {scalar.ndim}")

#vector tensor
vector=torch.tensor([7,7])
print(f"dimensions of vector -> {vector.ndim}")
print(f"shape of a vector -> {vector.shape}")

#MATRIX
matrix=torch.tensor([[7,8],
                    [9,10]])
print(f" generally capital letter used \n M = {matrix}")
print(f"dimensions of the matrix->{matrix.ndim}")
print(f"shape of a matrix ->{matrix.shape}")
print(f"0th axis -> {matrix[0]}")
print(f"1st axis ->{matrix[1]}")

"""according to dimension they may be called scalar,vector or matrix but they all are torch.tensor

"""

#TENSOR
T=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [5,6,7]]])
print(f"generally capital letter used \n T={T}")
print(f"dimensions of the tensor->{T.ndim}")
print(f"shape of the tensor->{T.shape} meaning we have 1 3*3 matrix")
print("tensor[1][0] goes out of bounds")
print(f"since python is 0 indexed for shape ([1,3,3]) first element in tensor([must be 0 ][row of matrix][column of matrix])-> \n {T[0][0]}")

"""###Random Tensors
-> used to initialize weights and then they are adjusted to better represent the data
"""

#creating random tensors of size (1,3,4)
random_tensor=torch.rand(1,3,4)
#can be written as random_tensor=torch.rand(size=(1,3,4))
print(random_tensor)
print(f"dimensions of the tensor->{random_tensor.ndim}")
print(f"shape of the tensor->{random_tensor.shape}")

#creating a random tensor similar to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))
print(random_image_size_tensor)
print("torch.randn(size=(height,width,color_channel))")
print(f"dimensions of the tensor->{random_image_size_tensor.ndim}")
print(f"shape of the tensor->{random_image_size_tensor.shape}")

# zeros and ones tensor
#used to create masks
zero_tensor=torch.zeros(1,3,4)
print(zero_tensor)
ones_tensor=torch.ones(1,3,4)
print(ones_tensor)
print(f"default data type = {ones_tensor.dtype}")

#creating a range of tensors and tensor-likes
one_to_ten=torch.arange(start=1,end=11,step=2)
print(one_to_ten)

ten_zeros=torch.zeros_like(one_to_ten)
print(ten_zeros)

"""###TENSOR DATATYPES

> **NOTE:** tensor dtypes one of 3 big errors with deeplearning and Pythorch
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on right device


"""

float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None)
print(f"default datatype {float_32_tensor.dtype}")
print("32 bit is single precision and 16 bit is half precision")

float_16_tensor=torch.tensor([3,6,9],dtype=torch.float16,#datatype of tensor
                             device=None,#what device is tensor on
                             requires_grad=False #whether or not to track tensor operations
                             )
print(float_16_tensor)

#convert tensor float_32_tensor to half precision
float_half=float_32_tensor.type(torch.half)

##sometimes different data types can still be multiplied
product=float_32_tensor * float_16_tensor
print(product)

#change device from CPU to GPU
float_32_tensor.to(device="cuda")

"""###getting info from tensors
1. to get dtype from a tensor -> tensor.dtype
2. to get shape from a tensor -> tensor.shape or tensor.size()
3. to get device from a tensor -> tensor.device
"""